name: Deploy

on:
    workflow_dispatch:
    release:
        types: [published]

jobs:
    deploy:
        name: Deploy App
        runs-on: ubuntu-latest

        environment:
            name: Production

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Deploy
              uses: hopinc/action@v1
              with:
                token: ${{ secrets.HOP_TOKEN }}