name: Deploy

on:
  workflow_dispatch:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy App
    runs-on: ubuntu-latest

    environment:
      name: Production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup hop.io CLI
        run: |
          curl -fsSL https://download.hop.sh/install | sh
          hop auth login --token ${{ secrets.HOP_TOKEN }}

      - name: Deploy to hop
        run: |
          hop deploy